import { StyleSheet } from "react-native";
import {
  ThemeColors,
  spacing,
  borderRadius,
  fontSize,
  fontWeight,
} from "../../constants/theme";

export const createStyles = (colors: ThemeColors) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.background,
    },
    scrollContent: {
      paddingBottom: spacing.xxxl * 2,
    },
    headerSection: {
      paddingHorizontal: spacing.lg,
      paddingTop: spacing.xl,
      paddingBottom: spacing.lg,
      backgroundColor: colors.surfaceElevated,
      borderBottomWidth: 1,
      borderBottomColor: colors.borderLight,
    },
    headerTitle: {
      fontSize: fontSize.xxl,
      fontWeight: fontWeight.bold,
      color: colors.text,
      marginBottom: spacing.xs,
      letterSpacing: -0.5,
    },
    headerSubtitle: {
      fontSize: fontSize.md,
      color: colors.textSecondary,
      lineHeight: 22,
    },
    jobInfo: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: colors.surfaceElevated,
      padding: spacing.lg,
      marginHorizontal: spacing.lg,
      marginTop: spacing.xl,
      borderRadius: borderRadius.xl,
      borderWidth: 1,
      borderColor: colors.borderLight,
      shadowColor: colors.shadow,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.05,
      shadowRadius: 12,
      elevation: 3,
      gap: spacing.md,
    },
    jobLogoContainer: {
      width: 56,
      height: 56,
      borderRadius: borderRadius.lg,
      backgroundColor: colors.surface,
      shadowColor: colors.shadow,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.05,
      shadowRadius: 4,
      elevation: 2,
      alignItems: "center",
      justifyContent: "center",
    },
    jobLogo: {
      width: 48,
      height: 48,
      borderRadius: borderRadius.md,
    },
    jobLogoFallback: {
      width: 48,
      height: 48,
      borderRadius: borderRadius.md,
      backgroundColor: colors.primaryLight,
      alignItems: "center",
      justifyContent: "center",
    },
    jobLogoText: {
      fontSize: fontSize.xl,
      fontWeight: fontWeight.bold,
      color: colors.primary,
    },
    jobInfoContent: {
      flex: 1,
      justifyContent: "center",
    },
    jobTitle: {
      fontSize: fontSize.lg,
      fontWeight: fontWeight.bold,
      color: colors.text,
      letterSpacing: -0.3,
      marginBottom: 4,
    },
    jobCompany: {
      fontSize: fontSize.sm,
      color: colors.textSecondary,
      fontWeight: fontWeight.medium,
    },
    formSection: {
      padding: spacing.lg,
      marginTop: spacing.md,
    },
    fieldContainer: {
      marginBottom: spacing.xl,
    },
    label: {
      fontSize: fontSize.sm,
      fontWeight: fontWeight.bold,
      color: colors.text,
      marginBottom: spacing.sm,
      letterSpacing: 0.2,
    },
    required: {
      color: colors.error,
    },
    input: {
      backgroundColor: colors.surfaceElevated,
      borderRadius: borderRadius.lg,
      paddingHorizontal: spacing.lg,
      paddingVertical: spacing.md + 4,
      fontSize: fontSize.md,
      color: colors.text,
      borderWidth: 1.5,
      borderColor: colors.borderLight,
    },
    inputFocused: {
      borderColor: colors.primary,
      backgroundColor: colors.surface,
      shadowColor: colors.primary,
      shadowOffset: { width: 0, height: 0 },
      shadowOpacity: 0.1,
      shadowRadius: 8,
      elevation: 2,
    },
    inputError: {
      borderColor: colors.error,
      backgroundColor: colors.surface,
    },
    textArea: {
      minHeight: 140,
      textAlignVertical: "top",
      paddingTop: spacing.lg,
    },
    errorText: {
      fontSize: fontSize.xs,
      color: colors.error,
      marginTop: spacing.xs,
      fontWeight: fontWeight.medium,
    },
    charCountContainer: {
      flexDirection: "row",
      justifyContent: "flex-end",
      marginTop: spacing.xs,
    },
    charCount: {
      fontSize: fontSize.xs,
      color: colors.textTertiary,
      fontWeight: fontWeight.medium,
    },
    charCountError: {
      color: colors.error,
    },
    submitButton: {
      flexDirection: "row",
      backgroundColor: colors.primary,
      borderRadius: borderRadius.full,
      paddingVertical: 18,
      marginHorizontal: spacing.lg,
      alignItems: "center",
      justifyContent: "center",
      marginTop: spacing.lg,
      shadowColor: colors.primary,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 12,
      elevation: 6,
      gap: spacing.sm,
    },
    submitButtonDisabled: {
      opacity: 0.6,
      shadowOpacity: 0,
      elevation: 0,
    },
    submitButtonText: {
      fontSize: fontSize.lg,
      fontWeight: fontWeight.bold,
      color: "#FFFFFF",
    },

    modalOverlay: {
      flex: 1,
      backgroundColor: "rgba(0, 0, 0, 0.7)",
      alignItems: "center",
      justifyContent: "center",
      padding: spacing.lg,
    },
    modalContent: {
      backgroundColor: colors.surfaceElevated,
      borderRadius: borderRadius.xl,
      padding: spacing.xxxl,
      alignItems: "center",
      width: "100%",
      maxWidth: 340,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 10 },
      shadowOpacity: 0.2,
      shadowRadius: 20,
      elevation: 10,
    },
    successIconContainer: {
      width: 88,
      height: 88,
      borderRadius: 44,
      backgroundColor: colors.success,
      alignItems: "center",
      justifyContent: "center",
      marginBottom: spacing.xl,
      shadowColor: colors.success,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 12,
      elevation: 6,
    },
    modalTitle: {
      fontSize: fontSize.xxl,
      fontWeight: fontWeight.bold,
      color: colors.text,
      marginBottom: spacing.md,
      textAlign: "center",
      letterSpacing: -0.5,
    },
    modalMessage: {
      fontSize: fontSize.md,
      color: colors.textSecondary,
      textAlign: "center",
      marginBottom: spacing.xxxl,
      lineHeight: 24,
    },
    boldText: {
      fontWeight: fontWeight.bold,
      color: colors.text,
    },
    modalButton: {
      backgroundColor: colors.primary,
      borderRadius: borderRadius.full,
      paddingVertical: spacing.md + 2,
      paddingHorizontal: spacing.xxxl,
      alignItems: "center",
      width: "100%",
    },
    modalButtonText: {
      fontSize: fontSize.md,
      fontWeight: fontWeight.bold,
      color: "#FFFFFF",
    },
  });