import { StyleSheet } from "react-native";
import {
  ThemeColors,
  spacing,
  borderRadius,
  fontSize,
  fontWeight,
} from "../../constants/theme";

export const createStyles = (colors: ThemeColors) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.background,
    },
    scrollContent: {
      paddingBottom: 130,
    },
    heroSection: {
      alignItems: "center",
      paddingVertical: spacing.xxxl,
      paddingHorizontal: spacing.lg,
      backgroundColor: colors.surfaceElevated,
      borderBottomLeftRadius: borderRadius.xl,
      borderBottomRightRadius: borderRadius.xl,
      shadowColor: colors.shadow,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.05,
      shadowRadius: 12,
      elevation: 3,
      marginBottom: spacing.md,
    },
    logoWrapper: {
      width: 96,
      height: 96,
      borderRadius: borderRadius.xl,
      backgroundColor: colors.surface,
      shadowColor: colors.shadow,
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.1,
      shadowRadius: 16,
      elevation: 5,
      marginBottom: spacing.xl,
      alignItems: "center",
      justifyContent: "center",
    },
    logoLarge: {
      width: 80,
      height: 80,
      borderRadius: borderRadius.lg,
    },
    logoFallbackLarge: {
      width: 80,
      height: 80,
      borderRadius: borderRadius.lg,
      backgroundColor: colors.primaryLight,
      alignItems: "center",
      justifyContent: "center",
    },
    logoFallbackText: {
      fontSize: fontSize.xxxl,
      fontWeight: fontWeight.bold,
      color: colors.primary,
    },
    jobTitle: {
      fontSize: fontSize.xxl,
      fontWeight: fontWeight.bold,
      color: colors.text,
      textAlign: "center",
      marginBottom: spacing.sm,
      letterSpacing: -0.5,
    },
    companyName: {
      fontSize: fontSize.lg,
      color: colors.textSecondary,
      fontWeight: fontWeight.medium,
      textAlign: "center",
      marginBottom: spacing.lg,
    },
    heroMeta: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: spacing.lg,
    },
    heroMetaItem: {
      flexDirection: "row",
      alignItems: "center",
      gap: spacing.xs,
    },
    heroMetaText: {
      fontSize: fontSize.sm,
      color: colors.textSecondary,
      fontWeight: fontWeight.medium,
    },
    section: {
      paddingHorizontal: spacing.lg,
      paddingVertical: spacing.xl,
    },
    sectionTitle: {
      fontSize: fontSize.xl,
      fontWeight: fontWeight.bold,
      color: colors.text,
      marginBottom: spacing.lg,
      letterSpacing: -0.3,
    },
    detailsGrid: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: spacing.md,
    },
    detailCard: {
      width: "47%",
      backgroundColor: colors.surfaceElevated,
      padding: spacing.lg,
      borderRadius: borderRadius.lg,
      borderWidth: 1,
      borderColor: colors.borderLight,
    },
    detailIconContainer: {
      width: 40,
      height: 40,
      borderRadius: borderRadius.md,
      backgroundColor: colors.primaryLight,
      alignItems: "center",
      justifyContent: "center",
      marginBottom: spacing.md,
    },
    detailLabel: {
      fontSize: fontSize.xs,
      color: colors.textTertiary,
      fontWeight: fontWeight.medium,
      textTransform: "uppercase",
      letterSpacing: 0.5,
      marginBottom: 4,
    },
    detailValue: {
      fontSize: fontSize.md,
      color: colors.text,
      fontWeight: fontWeight.bold,
    },
    salaryValue: {
      fontSize: fontSize.md,
      color: colors.primary,
      fontWeight: fontWeight.bold,
    },
    tagsContainer: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: spacing.sm,
    },
    tag: {
      backgroundColor: colors.surfaceElevated,
      paddingHorizontal: spacing.lg,
      paddingVertical: spacing.sm,
      borderRadius: borderRadius.full,
      borderWidth: 1,
      borderColor: colors.borderLight,
    },
    tagText: {
      fontSize: fontSize.sm,
      color: colors.textSecondary,
      fontWeight: fontWeight.semibold,
    },
    descriptionContainer: {
      backgroundColor: colors.surfaceElevated,
      padding: spacing.xl,
      borderRadius: borderRadius.xl,
      borderWidth: 1,
      borderColor: colors.borderLight,
      shadowColor: colors.shadow,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.05,
      shadowRadius: 12,
      elevation: 3,
    },
    descriptionContainerSecondary: {
      backgroundColor: colors.surfaceElevated,
      padding: spacing.xl,
      borderRadius: borderRadius.xl,
      borderWidth: 1,
      borderColor: colors.borderLight,
      marginTop: spacing.md,
    },
    descriptionText: {
      fontSize: fontSize.md,
      color: colors.textSecondary,
      lineHeight: 26,
    },
    requirementsTitle: {
      fontSize: fontSize.lg,
      fontWeight: fontWeight.bold,
      color: colors.text,
      marginBottom: spacing.md,
    },
    requirementRow: {
      flexDirection: "row",
      alignItems: "flex-start",
      gap: spacing.sm,
      marginBottom: spacing.sm,
    },
    requirementText: {
      flex: 1,
      fontSize: fontSize.md,
      color: colors.textSecondary,
      lineHeight: 22,
    },
    bottomBar: {
      position: "absolute",
      bottom: 0,
      left: 0,
      right: 0,
      flexDirection: "row",
      paddingHorizontal: spacing.lg,
      paddingVertical: spacing.lg,
      paddingBottom: spacing.xl,
      backgroundColor: colors.surfaceElevated,
      borderTopWidth: 1,
      borderTopColor: colors.borderLight,
      gap: spacing.md,
      shadowColor: colors.shadow,
      shadowOffset: { width: 0, height: -4 },
      shadowOpacity: 0.05,
      shadowRadius: 12,
      elevation: 10,
    },
    saveButton: {
      width: 90,
      height: 56,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      borderRadius: borderRadius.lg,
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.borderLight,
      gap: spacing.xs,
    },
    saveButtonSaved: {
      borderColor: colors.primary,
      backgroundColor: colors.primaryLight,
    },
    saveButtonText: {
      fontSize: fontSize.sm,
      fontWeight: fontWeight.semibold,
      color: colors.textSecondary,
    },
    saveButtonTextSaved: {
      color: colors.primary,
    },
    applyButton: {
      flex: 1,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      height: 56,
      borderRadius: borderRadius.lg,
      backgroundColor: colors.primary,
      gap: spacing.sm,
    },
    applyButtonText: {
      fontSize: fontSize.lg,
      fontWeight: fontWeight.bold,
      color: "#FFFFFF",
    },
  });