import { StyleSheet } from "react-native";
import { PaletteType, LIGHT_PALETTE } from "../JobFinder/JobFinderScreen.styles";

export const createStyles = (p: PaletteType = LIGHT_PALETTE, bottomInset: number = 0) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: p.cream,
    },
    scrollContent: {
      paddingBottom: 96 + bottomInset,
    },
    heroSection: {
      flexDirection: "row",
      alignItems: "flex-start",
      paddingVertical: 28,
      paddingHorizontal: 22,
      backgroundColor: p.white,
      borderBottomLeftRadius: 24,
      borderBottomRightRadius: 24,
      shadowColor: p.cardShadow,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 1,
      shadowRadius: 12,
      elevation: 3,
      marginBottom: 8,
      gap: 16,
    },
    heroTextGroup: {
      flex: 1,
    },
    companyLabel: {
      fontSize: 11,
      fontWeight: "700",
      color: p.cloudGray,
      textTransform: "uppercase",
      letterSpacing: 2,
      marginBottom: 6,
    },
    jobTitle: {
      fontSize: 24,
      fontWeight: "800",
      color: p.charcoal,
      letterSpacing: -0.5,
      lineHeight: 30,
      marginBottom: 14,
      fontFamily: undefined,
    },
    logoWrapper: {
      width: 64,
      height: 64,
      borderRadius: 16,
      backgroundColor: p.cream,
      borderWidth: 1,
      borderColor: p.hairline,
      shadowColor: p.deepShadow,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.12,
      shadowRadius: 8,
      elevation: 4,
      alignItems: "center",
      justifyContent: "center",
    },
    logoLarge: {
      width: 52,
      height: 52,
      borderRadius: 12,
    },
    logoFallbackLarge: {
      width: 52,
      height: 52,
      borderRadius: 12,
      backgroundColor: p.mintGreen,
      alignItems: "center",
      justifyContent: "center",
    },
    logoFallbackText: {
      fontSize: 22,
      fontWeight: "800",
      color: p.deepGreen,
    },
    heroMeta: {
      flexDirection: "row",
      alignItems: "center",
      flexWrap: "wrap",
      gap: 12,
    },
    heroMetaItem: {
      flexDirection: "row",
      alignItems: "center",
      gap: 4,
    },
    heroMetaText: {
      fontSize: 13,
      color: p.slate,
      fontWeight: "500",
    },
    section: {
      paddingHorizontal: 22,
      paddingVertical: 20,
    },
    sectionTitle: {
      fontSize: 18,
      fontWeight: "800",
      color: p.charcoal,
      marginBottom: 16,
      letterSpacing: -0.3,
    },
    detailsGrid: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 12,
    },
    detailCard: {
      width: "47%",
      backgroundColor: p.white,
      padding: 16,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: p.hairline,
    },
    detailLabel: {
      fontSize: 11,
      color: p.cloudGray,
      fontWeight: "600",
      textTransform: "uppercase",
      letterSpacing: 0.5,
      marginBottom: 4,
    },
    detailValue: {
      fontSize: 15,
      color: p.charcoal,
      fontWeight: "700",
    },
    salaryValue: {
      fontSize: 15,
      color: p.deepGreen,
      fontWeight: "700",
    },
    tagsContainer: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 8,
    },
    tag: {
      backgroundColor: p.mintGreen,
      paddingHorizontal: 14,
      paddingVertical: 8,
      borderRadius: 999,
    },
    tagText: {
      fontSize: 13,
      color: p.deepGreen,
      fontWeight: "700",
    },
    descriptionContainer: {
      backgroundColor: p.white,
      padding: 20,
      borderRadius: 20,
      borderWidth: 1,
      borderColor: p.hairline,
      shadowColor: p.cardShadow,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 1,
      shadowRadius: 12,
      elevation: 3,
    },
    descriptionContainerSecondary: {
      backgroundColor: p.white,
      padding: 20,
      borderRadius: 20,
      borderWidth: 1,
      borderColor: p.hairline,
      marginTop: 12,
    },
    descriptionText: {
      fontSize: 15,
      color: p.slate,
      lineHeight: 26,
    },
    requirementsTitle: {
      fontSize: 17,
      fontWeight: "700",
      color: p.charcoal,
      marginBottom: 12,
    },
    requirementRow: {
      flexDirection: "row",
      alignItems: "flex-start",
      gap: 8,
      marginBottom: 8,
    },
    requirementText: {
      flex: 1,
      fontSize: 15,
      color: p.slate,
      lineHeight: 22,
    },
    bottomBar: {
      position: "absolute",
      bottom: 0,
      left: 0,
      right: 0,
      paddingHorizontal: 22,
      paddingTop: 12,
      paddingBottom: bottomInset + 8,
      backgroundColor: p.cream,
      gap: 4,
    },
    saveButton: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      height: 40,
      borderRadius: 999,
      backgroundColor: p.white,
      borderWidth: 1,
      borderColor: p.hairline,
      gap: 8,
    },
    saveButtonSaved: {
      borderColor: p.deepGreen,
      backgroundColor: p.mintGreen,
    },
    saveButtonText: {
      fontSize: 15,
      fontWeight: "600",
      color: p.slate,
    },
    saveButtonTextSaved: {
      color: p.deepGreen,
    },
    applyButton: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      height: 46,
      borderRadius: 999,
      backgroundColor: p.deepGreen,
    },
    applyButtonText: {
      fontSize: 17,
      fontWeight: "700",
      color: "#FFFFFF",
    },
  });