import { StyleSheet } from "react-native";
import { PaletteType, LIGHT_PALETTE } from "../../screens/JobFinder/JobFinderScreen.styles";

export const createCardStyles = (p: PaletteType = LIGHT_PALETTE, isDark: boolean = false) =>
  StyleSheet.create({
    card: {
      borderRadius: 16,
      overflow: "hidden",
      backgroundColor: p.white,
      shadowColor: p.cardShadow,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 1,
      shadowRadius: 10,
      elevation: 3,
      position: "relative",
    },
    topSection: {
      backgroundColor: isDark ? p.hairline : "#FFFFFF",
      padding: 16,
      flexDirection: "row",
      alignItems: "flex-start",
    },
    topLeft: {
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
      flex: 1,
    },
    logoWrap: {
      width: 56,
      height: 56,
      borderRadius: 14,
      backgroundColor: isDark ? p.white : "#FFFFFF",
      alignItems: "center",
      justifyContent: "center",
      shadowColor: isDark ? "rgba(0,0,0,0.4)" : "rgba(0,0,0,0.08)",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 1,
      shadowRadius: 6,
      elevation: 3,
    },
    logo: {
      width: 40,
      height: 40,
      borderRadius: 8,
    },
    logoFallback: {
      fontSize: 20,
      fontWeight: "800",
      color: p.deepGreen,
    },
    companyName: {
      fontSize: 14,
      fontWeight: "600",
      color: p.charcoal,
      flex: 1,
    },
    bookmarkButton: {
      position: "absolute",
      top: 3,
      right: 2,
      zIndex: 10,
      width: 44,
      height: 44,
      alignItems: "center",
      justifyContent: "center",
    },
    bottomSection: {
      backgroundColor: isDark ? p.white : "#FFFFFF",
      padding: 16,
    },
    workModelChip: {
      alignSelf: "flex-start",
      backgroundColor: isDark ? p.hairline : "#F0F1F3",
      borderWidth: 1,
      borderColor: isDark ? "#48484A" : "#E0E2E6",
      borderRadius: 999,
      paddingVertical: 3,
      paddingHorizontal: 10,
      marginBottom: 8,
    },
    workModelText: {
      fontSize: 11,
      fontWeight: "600",
      color: isDark ? "#D1D1D6" : "#555555",
    },
    jobTitle: {
      fontSize: 18,
      fontWeight: "700",
      color: p.charcoal,
      letterSpacing: -0.3,
      lineHeight: 24,
    },
    metaText: {
      fontSize: 13,
      color: p.slate,
      fontWeight: "400",
      marginTop: 4,
    },
    footerRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginTop: 16,
    },
    tagsRow: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 6,
      flex: 1,
      marginRight: 12,
    },
    tag: {
      backgroundColor: isDark ? p.mintGreen : "#E8F2EC",
      borderRadius: 6,
      paddingVertical: 5,
      paddingHorizontal: 10,
    },
    tagText: {
      fontSize: 12,
      fontWeight: "600",
      color: p.deepGreen,
    },
    salaryColumn: {
      alignItems: "flex-end",
    },
    salaryText: {
      fontSize: 16,
      fontWeight: "800",
      color: p.charcoal,
      letterSpacing: -0.3,
    },
    salaryInterval: {
      fontSize: 11,
      fontWeight: "400",
      color: p.cloudGray,
      marginTop: 1,
    },
    salaryUndisclosed: {
      fontSize: 13,
      fontWeight: "600",
      color: isDark ? "#AAAAAA" : "#333333",
    },
  });